### ISSUE TITLE
Immediate Failure event-pipe error

### ISSUE THREAD

**Issue by sscotth** [themattrix/bash-concurrent#33]
I haven't been able to narrow when or how I get this error:

![screen shot 2018-09-28 at 12 15 48 am](https://user-images.githubusercontent.com/1010488/46189455-51f96200-c2b4-11e8-8486-13d63a6cd4fa.png)

But it usually occurs when I run quite a large script over and over again. Restarting the computer usually fixes this, but not always.

Once my system gets in this "state", I can't even run the demo.sh file in this repo.

On this system, the current `$TMPDIR` is `/var/folders/6b/mm5f4rz116lbp_9rphrmv4s00000gn/T/`

This line of code:

https://github.com/themattrix/bash-concurrent/blob/fc265c72219193bc5db810a70692bcf0896ed1f3/concurrent.lib.sh#L1078

`__crt__status_dir=$(mktemp -d "${TMPDIR:-/tmp}/concurrent.lib.sh.XXXXXXXXXXX")`

ultimately generates a `.../T//concurrent...` which is odd, but I don't think is the problem.

Interestingly, I can login to a different user account, and the demo file works, log back in to the original and still have the problem.

**Comment by jacoscaz** [comment]
I've just stumbled into this, apparently at random. I'm 99.9% sure I have not touched my script, which uses `concurrent` behind the scenes, but it suddenly broke.

**Comment by jacoscaz** [comment]
Just in case someone else stumbles into this, in my case this was due to something else having linked a recent version of GNU `sed` into my `$PATH`, overriding Mac OS' own version.
